import React from "react";
import { Box, Text, Group } from "@mantine/core";
import SolutionPatternTable from "../../../components/leaderboard/SolutionPatternTable/SolutionPatternTable";
import SectionTitle from "../../../components/common/SectionTitle/SectionTitle";
import { ModelMeta } from "../../../types";

interface PatternMetricsSectionProps {
  selectedModels: ModelMeta[];
}

const PatternMetricsSection: React.FC<PatternMetricsSectionProps> = ({
  selectedModels,
}) => {
  return (
    <>
      <SectionTitle
        title="Solution Pattern Analysis"
        subtitle="Analyze the patterns of solutions generated by each model."
        align="left"
      />

      {selectedModels.length === 0 ? (
        <Group justify="center" mt="md">
          <Text>
            Select one or more models to view their solution pattern analysis.
          </Text>
        </Group>
      ) : (
        <Box style={{ width: "100%", maxWidth: "100%" }} mt="md">
          <SolutionPatternTable models={selectedModels} />
        </Box>
      )}
    </>
  );
};

export default PatternMetricsSection;
